service: java-opencv-lambda

provider:
  name: aws
  region: ap-southeast-2
  profile: personal
  architecture: arm64
  ecr:
    images:
      appimage:
        path: ./docker

plugins:
  - serverless-better-credentials

functions:
  image-process:
    url:
      cors: true
    image:
      name: appimage