name: main

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Node Install Dependencies
        run: npm ci

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: ./build.sh

      - name: Serverless Deploy
        run: npm run deploy -- --stage dev

      - name: Run Lambda Function to check it loads
        run: curl --silent --show-error --fail https://47gjxgowcrvusxmfqkprkzfr7q0ospym.lambda-url.ap-southeast-2.on.aws/

#      - name: Run Load Test
#        run: # todo
